# Generated by Django 4.1.2 on 2022-10-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='firm',
            new_name='firm1',
        ),
    ]
