# Generated by Django 4.1.2 on 2022-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_firm_firm1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm1',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='firm1',
            name='adres',
        ),
        migrations.AddField(
            model_name='firm1',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='firm1',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='firm1',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование'),
        ),
    ]
